
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CrudOperation.Models
{

using System;
    using System.Collections.Generic;
    
public partial class LoaiTietKiem
{

    public int ID { get; set; }

    public string TenLoaiTietKiem { get; set; }

    public Nullable<bool> HoatDong { get; set; }

    public string MoTa { get; set; }

}

}
