

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CrudOperation.Models
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class SoTietKiemDBEntities : DbContext
{
    public SoTietKiemDBEntities()
        : base("name=SoTietKiemDBEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<LoaiTietKiem> LoaiTietKiems { get; set; }

    public virtual DbSet<PhieuGui> PhieuGuis { get; set; }

    public virtual DbSet<PhieuRut> PhieuRuts { get; set; }

    public virtual DbSet<TaiKhoanKhachHang> TaiKhoanKhachHangs { get; set; }

}

}

